version: '3.8'

services:
  api:
    container_name: api-container
    build: 
      context: ./app
      dockerfile: Dockerfile
    environment:
      DB_HOST: localhost
      DB_NAME: LZLTech
      DB_USER: SA
      DB_PASSWORD: 123_Mudar
    ports:
      - "9007:5000"
    restart: always
    networks:
      - lazuli-network
    depends_on:
      - db
  db:
    container_name: mssql-container
    build: 
      context: ./database
      dockerfile: Dockerfile
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 1450:1433
    volumes:
      - ./database/.docker:/var/opt/mssql/data
    restart: always
    networks:
      - lazuli-network
networks:
   lazuli-network:
     driver: bridge