version: '3.8'

services:
  api:
    container_name: api-container
    build: 
      context: ./Api
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: LZLtech
      DB_USER: SA
      DB_PASSWORD: Numsey#2022
    ports:
      - "9007:5000"
    restart: always
    networks:
      - minha-rede
    depends_on:
      - db
  db:
    container_name: mssql-container
    build: 
      context: ./Db
      dockerfile: Dockerfile
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 1450:1433
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql/data
    restart: always
    networks:
      - minha-rede
networks:
   minha-rede:
     driver: bridge